server:
  port: 8080
spring:
  profiles:
    active: dev
  elasticsearch:
    bboss:
      default:
        name: default
        elasticUser: elastic
        elasticPassword: changeme
        elasticsearch:
          discoverHost: true
          rest:
            hostNames: 127.0.0.1:9200
      logs:
        name: logs
        elasticUser: elastic
        elasticPassword: hmzj123456
        elasticsearch:
          discoverHost: true
          rest:
            hostNames: 192.168.1.244:9200
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9200
#      repositories:
#        enabled: true
  application:
    name: IDEAdemo1
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybase?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

#logging:
#  level:
#   com:
#    jarry.demo1:
#     mapper: debug