server:
  port: 8080
spring:
  elasticsearch:
    bboss:
      default:
        name: default
        elasticUser: elastic
        elasticPassword: changeme
        elasticsearch:
          discoverHost: true
          rest:
            hostNames: 127.0.0.1:9200
      logs:
        name: logs
        elasticUser: lalala
        elasticPassword: hmzj
        elasticsearch:
          discoverHost: true
          rest:
            hostNames: 116.62.29.167:9200
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9200
#      repositories:
#        enabled: true
  application:
    name: IDEAdemo1
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.191:3306/callcenter_user?characterEncoding=utf-8&useSSL=false
    username: ENC(lh5Or6q0rk3f2b9EgPJPoQ==)
    password: ENC(bEiBZQ/GyS0y5zDE1jXeNjdIyAEuy5FA)
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true