server:
  port: 8080
spring:
  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379
#  redis:
#    password: hmzj    # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）
#    cluster:
#      nodes:
#        - 192.168.1.244:7001
#        - 192.168.1.244:7002
#        - 192.168.1.244:7003
#        - 192.168.1.244:7004
#        - 192.168.1.244:7005
#        - 192.168.1.244:7000
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
  elasticsearch:
    bboss:
      default:
        name: default
        elasticUser: elastic
        elasticPassword: changeme
        elasticsearch:
          discoverHost: true
          rest:
            hostNames: 127.0.0.1:9200
#      logs:
#        name: logs
#        elasticUser: elastic
#        elasticPassword: hmzj123456
#        elasticsearch:
#          discoverHost: true
#          rest:
#            hostNames: 192.168.1.244:9200
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    prefix: classpath:/templates/
#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9200
#      repositories:
#        enabled: true
  application:
    name: IDEAdemo1
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybase?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
